#!/usr/bin/env python3

import rospy
from std_msgs.msg import Bool
from controller_manager_msgs.srv import SwitchController


class CollisionMonitor:
    def __init__(self, controller_name):
        self.controller_name = controller_name
        self.sub = rospy.Subscriber(
            "/online_collision_prediction", Bool, self.collision_cb
        )

    def collision_cb(self, msg):
        if msg.data:
            print("Collision anticipated. Stopping controller.")
            service = rospy.ServiceProxy(
                "/controller_manager/switch_controller", SwitchController
            )
            service(stop_controllers=[self.controller_name], strictness=2)


if __name__ == "__main__":
    rospy.init_node("controller_monitor")
    controller_name = rospy.get_param("/controller")
    rospy.logwarn(f"Monitoring collisions for controller '{controller_name}'")
    cm = CollisionMonitor(controller_name)
    rospy.spin()
