#!/usr/bin/env python3

import rospy
import moveit_commander

from geometry_msgs.msg import PoseStamped

import sys

def spawn():
    moveit_commander.roscpp_initialize(sys.argv)
    rospy.init_node("scene_spawner", anonymous=True)

    # robot = moveit_commander.RobotCommander()
    scene = moveit_commander.PlanningSceneInterface()

    # table
    box_name = 'table'
    box_pose = PoseStamped()
    box_pose.pose.orientation.x = -1.48202e-24
    box_pose.pose.orientation.y =  8.65956e-17
    box_pose.pose.orientation.z = -0.707107
    box_pose.pose.orientation.w =  0.707107
    box_pose.pose.position.x =  0.29
    box_pose.pose.position.y = -0.17
    box_pose.pose.position.z = -0.325
    box_pose.header.frame_id = 'panda_link0'
    scene.add_box(box_name, box_pose, size=(0.62, 1.41, 0.625))

    # mount plate
    box_name = 'mount_plate'
    box_pose.pose.position.x = -0.0385
    box_pose.pose.position.y = -0.0
    box_pose.pose.position.z = -0.01
    scene.add_box(box_name, box_pose, size=(.26, .25, 0.02))

    # Glass table
    box_name = "glass_table"
    box_pose.pose.position.x = -0.03
    box_pose.pose.position.y = 0.16 + 0.55
    box_pose.pose.position.z = -0.14
    scene.add_box(box_name, box_pose, size=(1.10, 1.42, 1.02))

    # Left beam
    box_name = "beam_left"
    box_pose.pose.position.x = -0.74 + 0.05
    box_pose.pose.position.y = 0.16 + 0.03
    box_pose.pose.position.z = .36 + 1.235/2
    scene.add_box(box_name, box_pose, size=(0.11, 0.11, 1.235)) # with safety width

    # Left holder
    box_name = "holder_left"
    box_pose.pose.position.x = -0.74 + 0.05
    box_pose.pose.position.y = 0.19 - 0.101
    box_pose.pose.position.z = .36 + 0.65 + 0.24/2
    scene.add_box(box_name, box_pose, size=(0.12, 0.12, 0.30)) # with safety width

    # Left holder lower
    box_name = "holder_left_lower"
    box_pose.pose.position.x = -0.74 + 0.03
    box_pose.pose.position.y = 0.19 - 0.101
    box_pose.pose.position.z = 0.36 + .07 - 0.38/2
    scene.add_box(box_name, box_pose, size=(0.12, 0.12, 0.38)) # with safety width

    # Right beam
    box_name = "beam_right"
    box_pose.pose.position.x = 0.68 - 0.03
    box_pose.pose.position.y = 0.16 + 0.03
    box_pose.pose.position.z = .36 + 1.235/2
    scene.add_box(box_name, box_pose, size=(0.11, 0.11, 1.235))

    # Right holder
    box_name = "holder_right"
    box_pose.pose.position.x = 0.68 - 0.13
    box_pose.pose.position.y = 0.19 - 0.021
    box_pose.pose.position.z = .36 + 0.64 + 0.24/2
    scene.add_box(box_name, box_pose, size=(0.12, 0.12, 0.24))

    # Vicon right
    box_name = "vicon_right"
    box_pose.pose.position.x = 0.68 - 0.14
    box_pose.pose.position.y = .45
    box_pose.pose.position.z = .36 + 0.36/2
    scene.add_box(box_name, box_pose, size=(0.30, 0.28, 0.36))

    # Extra safety left
    box_name = "extra_safety_left"
    box_pose.pose.position.x = -0.46
    box_pose.pose.position.y = .10
    box_pose.pose.position.z = -0.14
    scene.add_box(box_name, box_pose, size=(0.10, 0.54, 1.02))

    # Extra safety right
    box_name = "extra_safety_right"
    box_pose.pose.position.x = 0.43
    box_pose.pose.position.y = .10
    box_pose.pose.position.z = -0.14
    scene.add_box(box_name, box_pose, size=(0.10, 0.54, 1.02))

if __name__ == '__main__':
    spawn()
